name = "Distributed2Coloring"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Distributed2Coloring"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[lean_lib]]
name = "Distributed2Coloring"
moreLeanArgs = ["-j", "1"]
